"use client";

import Link from "next/link";
import { useState, useEffect } from "react";
import { generateReply } from "@/lib/ai-reply";

const DEFAULT = { name: "Your Business", slug: "demo" };

type FB = { id: string; rating: number; message: string; name: string | null; date: string; done: boolean };

const MOCK: FB[] = [
  { id: "1", rating: 2, message: "Arrived late and didn't explain extra charges.", name: "Sarah M.", date: "Aug 28", done: false },
    { id: "2", rating: 1, message: "Job incomplete. Never came back.", name: "James R.", date: "Aug 27", done: false },
      { id: "3", rating: 3, message: "Okay work but price felt high.", name: null, date: "Aug 26", done: true },
      ];

      export default function DashboardPage() {
        const [biz, setBiz] = useState(DEFAULT);
          const [fb, setFb] = useState(MOCK);
            const [filter, setFilter] = useState<"all" | "open" | "done">("all");
              const [copied, setCopied] = useState(false);
                const [rating, setRating] = useState(5);
                  const [text, setText] = useState("");
                    const [reply, setReply] = useState("");
                      const [rCopied, setRCopied] = useState(false);

                        useEffect(() => {
                            try {
                                  const s = localStorage.getItem("rf_business");
                                        if (s) {
                                                const p = JSON.parse(s);
                                                        setBiz({ name: p.name || DEFAULT.name, slug: p.slug || DEFAULT.slug });
                                                              }
                                                                  } catch {}
                                                                    }, []);

                                                                        const link = (typeof window !== "undefined" ? window.location.origin : "https://reputationflow-zrpt.vercel.app") + "/r/" + biz.slug;

                                                                                const qr = `https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(link)}&bgcolor=000000&color=e7e9ea`;

                                                                                  const list = fb.filter((i) => filter === "all" || (filter === "open" ? !i.done : i.done));
                                                                                    const open = fb.filter((i) => !i.done).length;

                                                                                      return (
                                                                                          <div className="min-h-screen bg-black text-[#e7e9ea]">
                                                                                                <header className="sticky top-0 z-50 bg-black/80 border-b border-[#2f3336]">
                                                                                                        <div className="max-w-5xl mx-auto px-4 h-14 flex items-center justify-between">
                                                                                                                  <div className="flex items-center gap-2">
                                                                                                                              <div className="w-8 h-8 rounded-full bg-[#1d9bf0] flex items-center justify-center text-white font-bold text-sm">RF</div>
                                                                                                                                          <span className="font-bold">ReputationFlow</span>
                                                                                                                                                    </div>
                                                                                                                                                              <div className="flex gap-4 text-sm text-[#71767b]">
                                                                                                                                                                          <span className="hidden sm:inline">{biz.name}</span>
                                                                                                                                                                                      <Link href="/">Log out</Link>
                                                                                                                                                                                                </div>
                                                                                                                                                                                                        </div>
                                                                                                                                                                                                              </header>

                                                                                                                                                                                                                    <main className="max-w-5xl mx-auto px-4 py-8 space-y-6">
                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                      <h1 className="text-2xl font-bold">Dashboard</h1>
                                                                                                                                                                                                                                                <p className="text-[#71767b] text-sm mt-1">Smart link, private feedback & AI replies</p>
                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                                                                                                                                                                                                                                                                          {[
                                                                                                                                                                                                                                                                                      ["Review requests", "47"],
                                                                                                                                                                                                                                                                                                  ["Private feedback", String(fb.length)],
                                                                                                                                                                                                                                                                                                              ["Open issues", String(open)],
                                                                                                                                                                                                                                                                                                                          ["Avg rating", "4.7"],
                                                                                                                                                                                                                                                                                                                                    ].map(([l, v]) => (
                                                                                                                                                                                                                                                                                                                                                <div key={l} className="rounded-2xl border border-[#2f3336] bg-[#16181c] p-4">
                                                                                                                                                                                                                                                                                                                                                              <p className="text-xs text-[#71767b]">{l}</p>
                                                                                                                                                                                                                                                                                                                                                                            <p className="text-2xl font-bold mt-1">{v}</p>
                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="grid sm:grid-cols-5 gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="sm:col-span-3 rounded-2xl border border-[#2f3336] bg-[#16181c] p-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2 className="font-bold text-sm mb-1">Smart Review Link</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-xs text-[#71767b] mb-3">4–5★ → Google · 1–3★ → private</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex gap-2 rounded-xl border border-[#2f3336] bg-black px-3 py-2 mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <code className="flex-1 text-[#1d9bf0] text-xs truncate">{link}</code>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={() => { navigator.clipboard.writeText(link); setCopied(true); setTimeout(() => setCopied(false), 2000); }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="bg-[#1d9bf0] text-white text-xs font-bold px-3 py-1 rounded-lg">{copied ? "Copied" : "Copy"}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href={`/r/${biz.slug}`} target="_blank" className="text-xs font-bold border border-[#2f3336] rounded-full px-4 py-2 inline-block">Preview</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="sm:col-span-2 rounded-2xl border border-[#2f3336] bg-[#16181c] p-5 flex flex-col items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 className="font-bold text-sm self-start mb-2">QR Code</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img src={qr} alt="QR" width={140} height={140} className="rounded-xl" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="rounded-2xl border border-[#2f3336] bg-[#16181c] p-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex justify-between items-center mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="font-bold text-sm">Private Feedback</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex gap-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {(["all", "open", "done"] as const).map((f) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button key={f} onClick={() => setFilter(f)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className={`text-xs font-bold px-3 py-1 rounded-full capitalize ${filter === f ? "bg-[#1d9bf0] text-white" : "border border-[#2f3336] text-[#71767b]"}`}>{f}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {list.map((i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={i.id} className="rounded-xl border border-[#2f3336] bg-black p-4 flex justify-between gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-[#1d9bf0] text-sm">{"★".repeat(i.rating)}{"☆".repeat(5 - i.rating)} <span className="text-[#71767b]">{i.name || "Anon"} · {i.date}</span></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-sm mt-1">{i.message}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={() => setFb((p) => p.map((x) => x.id === i.id ? { ...x, done: !x.done } : x))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className={`text-xs font-bold px-3 py-1 rounded-full h-fit ${i.done ? "bg-green-500/20 text-green-400" : "bg-[#1d9bf0]/20 text-[#1d9bf0]"}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {i.done ? "Done" : "Resolve"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="rounded-2xl border border-[#2f3336] bg-[#16181c] p-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="font-bold text-sm mb-1">AI Reply</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-xs text-[#71767b] mb-3">Paste a review, get a professional response</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex flex-col sm:flex-row gap-3 mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <select value={rating} onChange={(e) => setRating(+e.target.value)} className="rounded-xl border border-[#2f3336] bg-black px-3 py-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {[5, 4, 3, 2, 1].map((r) => <option key={r} value={r}>{r} stars</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input value={text} onChange={(e) => setText(e.target.value)} placeholder="Paste review text..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="flex-1 rounded-xl border border-[#2f3336] bg-black px-3 py-2 text-sm" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={() => text.trim() && setReply(generateReply({ rating, reviewText: text, businessName: biz.name }))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="bg-[#1d9bf0] text-white text-sm font-bold px-5 py-2 rounded-full">Generate</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {reply && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="mt-4 rounded-xl border border-[#2f3336] bg-black p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-sm whitespace-pre-wrap mb-2">{reply}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => { navigator.clipboard.writeText(reply); setRCopied(true); setTimeout(() => setRCopied(false), 2000); }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="text-xs font-bold border border-[#2f3336] px-3 py-1 rounded-lg">{rCopied ? "Copied" : "Copy"}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }